openapi: 3.1.0
info:
  title: Workeas
paths:
  /api/tasks/:
    get:
      summary: Api Get Tasks
      operationId: api_get_tasks_api_tasks__get
      parameters:
        - name: priority
          in: query
          required: false
          schema:
            anyOf:
              - type: string
              - type: 'null'
            title: Priority
        - name: date
          in: query
          required: false
          schema:
            anyOf:
              - type: string
                format: date-time
              - type: 'null'
            title: Date
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/tasks/{task_id}:
    get:
      summary: Api Get Task
      operationId: api_get_task_api_tasks__task_id__get
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
            title: Task Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/tasks/add/:
    post:
      summary: Api Add Task
      operationId: api_add_task_api_tasks_add__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/tasks/delete/{task_id}:
    get:
      summary: Api Delete Task
      operationId: api_delete_task_api_tasks_delete__task_id__get
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
            title: Task Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /tasks/:
    get:
      summary: Get Tasks
      operationId: get_tasks_tasks__get
      parameters:
        - name: priority
          in: query
          required: false
          schema:
            anyOf:
              - type: integer
              - type: 'null'
            title: Priority
        - name: date
          in: query
          required: false
          schema:
            anyOf:
              - type: string
                format: date-time
              - type: 'null'
            title: Date
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /tasks/add:
    get:
      summary: Add Task
      operationId: add_task_tasks_add_get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string
    post:
      summary: Add Task
      operationId: add_task_tasks_add_post
      responses:
        '307':
          description: Successful Response
  /tasks/delete/{task_id}:
    get:
      summary: Delete Task
      operationId: delete_task_tasks_delete__task_id__get
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
            title: Task Id
      responses:
        '307':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Priority:
      type: integer
      enum:
        - 0
        - 1
        - 2
        - 3
      title: Priority
    Task:
      properties:
        title:
          type: string
          title: Title
        description:
          type: string
          title: Description
        date:
          type: string
          format: date-time
          title: Date
        priority:
          $ref: '#/components/schemas/Priority'
        id:
          type: integer
          title: Id
      type: object
      required:
        - title
        - description
        - date
        - priority
        - id
      title: Task
    TaskCreate:
      properties:
        title:
          type: string
          title: Title
        description:
          type: string
          title: Description
        date:
          type: string
          format: date-time
          title: Date
        priority:
          $ref: '#/components/schemas/Priority'
      type: object
      required:
        - title
        - description
        - date
        - priority
      title: TaskCreate
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
